AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: REST API set up using SAM (in Udemy course section 7)

Globals:
  Function:
    Runtime: nodejs8.10
    Environment:
      Variables:
        TABLE_NAME: !Ref Table
    MemorySize: 128
    Timeout: 5

Resources:
  Table:
    Type: AWS::Serverless::SimpleTable   # generate a DynamoDB table at the backend
    Properties:
      PrimaryKey:
        Name: userid
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  GetUser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get.handler        # use get method
      Policies: AmazonDynamoDBReadOnlyAccess  # permission policy to use db read/only (to get)
      Events:
        GetUser:                 # endpoint
          Type: Api
          Properties:
            Path: /user/{userid} # endpoint URL - NB userid as a parameter in code
            Method: get

  PostUser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: post.handler   # use post method
      Policies: AmazonDynamoDBFullAccess  # permission policy to use db read/write (to post)
      Events:
        GetUser:              # endpoint
          Type: Api
          Properties:
            Path: /user/{userid} # endpoint URL - NB userid as a parameter in code
            Method: post       # could actually be either put or post here
  DeleteUser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: delete.handler   # use post method
      Policies: AmazonDynamoDBFullAccess  # permission policy to use db read/write (to delete)
      Events:
        GetUser:              # endpoint
          Type: Api
          Properties:
            Path: /user/{userid} # endpoint URL - NB userid as a parameter in code
            Method: delete